---
# install_* actions ------------------------------------------------------------
# [name: str, state: str] ------------------------------------------------------
role_packages:
  - name: nvidia
    status: absent
  - name: nvidia-lts
    status: absent
  - name: nvidia-dkms
    state: absent
# role_flatpaks: []
role_AUR: [nvidia-580xx-dkms]

# manage_services action -------------------------------------------------------
# [name: str, enabled: bool, state: str] ---------------------------------------
# role_services: []

# *_files_data actions ---------------------------------------------------------
# Directories must end in trailing slash ---------------------------------------
# [src: path, dest: path, become: bool] ----------------------------------------
# files_data:
#   - src: '{{ role_dir }}/files/'
#   - dest: '{{ ansible_facts["user"] }}/.config/{{ role_name }}/'
