---
# install_* actions ------------------------------------------------------------
# [name: str, state: str] ------------------------------------------------------
role_packages: [otf-firamono-nerd, noto-fonts-cjk]
# role_flatpaks: []
# role_AUR: []

# manage_services action -------------------------------------------------------
# [name: str, enabled: bool, state: str] ---------------------------------------
# role_services: []

# *_files_data actions ---------------------------------------------------------
# Directories must end in trailing slash ---------------------------------------
# [src: path, dest: path, become: bool] ----------------------------------------
# files_data:
#   - src: '{{ role_path }}/files/'
#   - dest: '{{ ansible_facts["user"] }}/.config/{{ role_name }}/'
