---
# install_* actions ------------------------------------------------------------
# [name: str, state: str] ------------------------------------------------------
# role_packages: []
# role_flatpaks: []

# manage_services action -------------------------------------------------------
# [name: str, enabled: bool, state: str] ---------------------------------------
# role_services: []

# *_files_data actions ---------------------------------------------------------
# Directories must end in trailing slash ---------------------------------------
# [src: path, dest: path, become: bool] ----------------------------------------
files_data:
  - src: "{{ role_path }}/files/"
    dest: "/tmp/ansible-symlink/"
  - src: "{{ role_path }}/files/"
    dest: "/tmp/ansible-copy/"
