---
- name: Ensure tmp directories are removed
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  loop:
    - /tmp/ansible-symlink
    - /tmp/ansible-copy

- name: Remove bc package
  ansible.builtin.package:
    name: bc
    state: absent
